pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
stage('Deploy') {
      steps {
        script {
                    def installNginx = '''
                        # Update package list
                        sudo apt-get update
                        
                        # Install Nginx
                        sudo apt-get install -y nginx
                    '''
                    // Execute the shell commands
                    sh installNginx
                }
      }
    }
  }
}
